# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: "Eslint Linter"
          command: npm run eslint -- -f junit -o reports/junit/eslint-result.xml --color
      - store_test_results:
          path: reports/junit
      - store_test_results:
          path: reports/junit

  deploy-dev:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: clever deploy
          command: |
            git remote add clever https://$CLEVER_TOKEN:$CLEVER_SECRET@push-par-clevercloud-customers.services.clever-cloud.com/$APP_ID.git
            git push -u clever master

  deploy-prod:
    docker:
      - image: circleci/node:8.9.
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Avoid prompt authentication check
          command: echo -e "Host push-par-clevercloud-customers.services.clever-cloud.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Git push to clever cloud
          command: |
            git remote add clever git+ssh://git@push-par-clevercloud-customers.services.clever-cloud.com/app_bf78b874-c49e-4032-8a2c-d3ce0c11ce6a.git
            git push -u clever master


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - deploy-dev
          filters:
            branches:
              only: master