export default {
    LEFT_SIDE_MENU_DID_MOUNT: 'LEFT_SIDE_MENU_DID_MOUNT',
    TOGGLE_LEFT_SIDE_MENU_VISIBILITY: 'TOGGLE_LEFT_SIDE_MENU_VISIBILITY',

    /* FETCHING RESSOURCES */
    FETCH_HOTSPOTS_BY_CITY: 'FETCH_HOTSPOTS_BY_CITY',
    FETCH_HOTSPOTS_BY_CITY_SUCCESS: 'FETCH_HOTSPOTS_BY_CITY_SUCCESS',
    FETCH_HOTSPOTS_BY_CITY_ERROR: 'FETCH_HOTSPOTS_BY_CITY_ERROR',
    FETCH_HOTSPOT_SUCCEDED: 'FETCH_HOTSPOT_SUCCEDED',
    FETCH_HOTSPOT_FAILED: 'FETCH_HOTSPOT_FAILED',
    FETCH_MESSAGES_SUCCEDED: 'FETCH_MESSAGES_SUCCEDED',
    FETCH_MESSAGES_FAILED: 'FETCH_MESSAGES_FAILED',
    FETCH_MESSAGE_COMMENTS: 'FETCH_MESSAGE_COMMENTS',
    COMMENTS_COUNT_FETCHED: 'COMMENTS_COUNT_FETCHED',
    FETCH_MESSAGE_COMMENTS_SUCCEDED: 'FETCH_MESSAGE_COMMENTS_SUCCEDED',
    FETCH_MESSAGE_COMMENTS_FAILED: 'FETCH_MESSAGE_COMMENTS_FAILED',

    /* PERSIST RESSOURCES */
    POST_SETTING_UP_HOTSPOT_FORM_DATA: 'POST_SETTING_UP_HOTSPOT_FORM_DATA',
    POST_EDITION_MESSAGE_FORM_DATA: 'POST_EDITION_MESSAGE_FORM_DATA',
    PERSIST_MESSAGE_COMMENT: 'PERSIST_MESSAGE_COMMENT',
    NEW_HOTSPOT_SAVED: 'NEW_HOTSPOT_SAVED',
    NEW_MESSAGE_SAVED: 'NEW_MESSAGE_SAVED',
    NEW_COMMENT_SAVED: 'NEW_COMMENT_SAVED',
    ALERT_STILL_EXIST: 'ALERT_STILL_EXIST',
    HOTSPOT_AVATAR_UPLOADED: 'HOTSPOT_AVATAR_UPLOADED',
    ALERT_HOTSPOT_IMAGE_UPLOADED: 'ALERT_HOTSPOT_IMAGE_UPLOADED',
    DELETE_HOTSPOT_MESSAGE: 'DELETE_HOTSPOT_MESSAGE',
    DELETE_MESSAGE_COMMENT: 'DELETE_COMMENT_MESSAGE',
    HOTSPOT_MESSAGE_DELETED: 'HOTSPOT_MESSAGE_DELETED',
    HOTSPOT_COMMENT_DELETED: 'HOTSPOT_COMMENT_DELETED',

    /* FORM AND EDITION ACTIONS */
    EDIT_HOTSPOT_MESSAGE: 'EDIT_HOTSPOT_MESSAGE',
    EDIT_HOTSPOT: 'EDIT_HOTSPOT',
    DISPLAY_SETTING_UP_HOTSPOT_MESSAGE_FORM: 'DISPLAY_SETTING_UP_HOTSPOT_MESSAGE_FORM',
    CLEAR_HOTSPOT_MESSAGE_EDITION: 'CLEAR_HOTSPOT_MESSAGE_EDITION',
    CLEAR_HOTSPOT_EDITION: 'CLEAR_HOTSPOT_EDITION',

    SUBMIT_HOSTPOT_ADDRESS_MODAL: 'SUBMIT_HOSTPOT_ADDRESS_MODAL',
    SAVE_IN_STATE_SETTING_UP_HOTSPOT_FORM_DATA: 'SAVE_IN_STATE_SETTING_UP_HOTSPOT_FORM_DATA',

    /* SOCIALS NETWORK ACTIONS */
    HOTSPOT_VIEW_UP: 'HOTSPOT_VIEW_UP',

    /* COMPONENTS STATE */
    OPEN_HOSTPOT_ADDRESS_MODAL: 'OPEN_HOSTPOT_ADDRESS_MODAL',
    CLOSE_HOSTPOT_ADDRESS_MODAL: 'CLOSE_HOSTPOT_ADDRESS_MODAL',

    OPEN_HOTSPOT_IN_SPA_MODAL: 'OPEN_HOTSPOT_IN_SPA_MODAL',
    CLOSE_HOTSPOT_IN_SPA_MODAL: 'CLOSE_HOTSPOT_IN_SPA_MODAL',

    OPEN_HOTSPOT_IN_UNIVERSAL_MODAL: 'OPEN_HOTSPOT_IN_UNIVERSAL_MODAL',
    CLOSE_HOTSPOT_IN_UNIVERSAL_MODAL: 'CLOSE_HOTSPOT_IN_UNIVERSAL_MODAL',

    OPEN_SETTING_UP_HOTSPOT_MODAL: 'OPEN_SETTING_UP_HOTSPOT_MODAL',
    CLOSE_SETTING_UP_HOTSPOT_MODAL: 'CLOSE_SETTING_UP_HOTSPOT_MODAL',

    CANCEL_HOTSPOT_SETTING_UP: 'CANCEL_HOTSPOT_SETTING_UP:',

    /* WIDGETS THINGS */
    SAVE_SLIDESHOWS_PICTURES: 'SAVE_SLIDESHOWS_PICTURES',
    SELECT_WIDGET_TO_CONFIGURE: 'SELECT_WIDGET_TO_CONFIGURE',
    UNSELECT_WIDGET_TO_CONFIGURE: 'UNSELECT_WIDGET_TO_CONFIGURE',

    /* MAP NAVIGATION */
    FOCUS_HOTSPOT_IN_SEARCH_LIST: 'FOCUS_HOTSPOT_IN_SEARCH_LIST',
    FOCUS_HOTSPOT_IN_MAP: 'FOCUS_HOTSPOT_IN_MAP',
    UNFOCUS_HOTSPOT_IN_MAP: 'UNFOCUS_HOTSPOT_IN_MAP',
    MAP_MOVED: 'MAP_MOVED',
    CENTER_MAP_TO_POSITION: 'CENTER_MAP_TO_POSITION',
    NEW_MARKER_DROPPED: 'NEW_MARKER_DROPPED',

    /* Algolia events */
    HOTSPOT_SEARCH_KEY_PRESS: 'HOTSPOT_SEARCH_KEY_PRESS',
    ALGOLIA_ERROR: 'ALGOLIA_ERROR',
    DISPLAY_HITS: 'DISPLAY_HITS',

    /* Google APIs */
    REVERSED_GEOCODING_STARTED: 'REVERSED_GEOCODING_STARTED',
    REVERSED_GEOCODING_SUCCEDED: 'REVERSED_GEOCODING_SUCCEDED',
    REVERSED_GEOCODING_FAILED: 'REVERSED_GEOCODING_FAILED',
    GEOCODING_STARTED: 'GEOCODING_STARTED',
    GEOCODING_SUCCEDED: 'GEOCODING_SUCCEDED',
    GEOCODING_FAILED: 'GEOCODNIG_FAILED',

    /* FileStack API */
    REMOVE_IMAGE_WITH_HANDLE: 'REMOVE_IMAGE_WITH_HANDLE',

    /* GPS */
    INIT_HOTSPOT_FROM_MY_POSITION: 'INIT_HOTSPOT_FROM_MY_POSITION',
    SET_GPS_POSITION: 'SET_GPS_POSITION',
    ON_GPS_ERROR: 'ON_GPS_ERROR',
    SET_POSITION_TO_EDITED_HOTSPOT: 'SET_POSITION_TO_EDITED_HOTSPOT',

    /* Notifications */
    DISPLAY_MESSAGE_TO_SCREEN: 'DISPLAY_MESSAGE_TO_SCREEN',
    MESSAGE_TO_SCREEN_ON_DISAPEAR: 'MESSAGE_TO_SCREEN_ON_DISAPEAR',

    REDIRECT_TO: 'REDIRECT_TO',

    /* LOADERS / SPINNERS */
    DELETE_SLIDESHOW_IMAGE_REQUESTED: 'DELETE_SLIDESHOW_IMAGE_REQUESTED',
    DELETE_SLIDESHOW_IMAGE_ENDED: 'DELETE_SLIDESHOW_IMAGE_ENDED',

    /* DROP MARKERS UX */
    SHOW_HOTSPOT_TYPE_DESCRIPTION_MODAL: 'SHOW_HOTSPOT_TYPE_DESCRIPTION_MODAL',
    TOGGLE_DROP_MARKER_MOD: 'TOGGLE_DROP_MARKER_MOD',
    INIT_SETTING_UP_MODE: 'INIT_SETTING_UP_MODE',

    /* SUBMIT LEADS */
    SUBMIT_LEAD: 'SUBMIT_LEAD',
    /* ANALYTICS */
    TRACK_EVENT: 'TRACK_EVENT',
};
