export default {
    TOGGLE_LEFT_SIDE_MENU_VISIBILITY: 'TOGGLE_LEFT_SIDE_MENU_VISIBILITY',
    LEFT_SIDE_MENU_DID_MOUNT: 'LEFT_SIDE_MENU_DID_MOUNT',
    FETCH_HOTSPOTS_BY_CITY: 'FETCH_HOTSPOTS_BY_CITY',
    FETCH_HOTSPOTS_BY_CITY_SUCCESS: 'FETCH_HOTSPOTS_BY_CITY_SUCCESS',
    FETCH_HOTSPOTS_BY_CITY_ERROR: 'FETCH_HOTSPOTS_BY_CITY_ERROR',
    HOTSPOT_SEARCH_KEY_PRESS: 'HOTSPOT_SEARCH_KEY_PRESS',
    DISPLAY_HITS: 'DISPLAY_HITS',
    ALGOLIA_ERROR: 'ALGOLIA_ERROR',
};
